# Version 3+ needed for secrets
version: '3.8'

services:
# Deploy 2 vote-app nodes
  vote-app:
    image: bretfisher/examplevotingapp_vote
    ports:
      - 80:80
    networks:
      - frontend
    deploy:
      replicas: 2

# Deploy postgres db    
  db:
    image: postgres:9.4
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/my_secret_data
      POSTGRES_HOST_AUTH_METHOD: trust
    deploy:
      replicas: 1
    volumes:
      - db-data:/var/lib/postgresql/data
    secrets:
      - my_secret_data

# Deploy redis node
  redis:
    image: redis:3.2
    networks:
      - frontend
    deploy:
      replicas: 1

# Deploy worker node
  worker:
    image: bretfisher/examplevotingapp_worker
    networks:
      - frontend
      - backend
    deploy:
      replicas: 1
    
# Deploy results node
  results:
    image: bretfisher/examplevotingapp_result
    ports:
      - 5001:80
    networks:
      - backend
    deploy:
      replicas: 1
    
# Create frontend/backend networks
networks:
  frontend:
    driver: overlay
  backend:
    driver: overlay

# Create persistent db-data volume
volumes:
  db-data:

# Specify my_secret_data has already been created within Docker CLI
secrets:
  my_secret_data:
    external: True