version: '3.8'

services:
  vote-app:
    image: bretfisher/examplevotingapp_vote
    ports:
      - 80:80
    networks:
      - frontend
    deploy:
      replicas: 2
    
  db:
    image: postgres:9.4
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/my_secret_data
      POSTGRES_HOST_AUTH_METHOD: trust
    deploy:
      replicas: 1
    volumes:
      - db-data:/var/lib/postgresql/data
    secrets:
      - my_secret_data

  redis:
    image: redis:3.2
    networks:
      - frontend
    deploy:
      replicas: 1

  worker:
    image: bretfisher/examplevotingapp_worker
    networks:
      - frontend
      - backend
    deploy:
      replicas: 1
    
  results:
    image: bretfisher/examplevotingapp_result
    ports:
      - 5001:80
    networks:
      - backend
    deploy:
      replicas: 1
    
networks:
  frontend:
    driver: overlay
  backend:
    driver: overlay

volumes:
  db-data:

secrets:
  my_secret_data:
    external: True